import streamlit as st
import llm_model
import html_scrapping
from dataset_creation import convert_time_column,convert_to_lead_dataframe
from param import TIME_WINDOW

st.set_page_config(page_title="Lead Generation")

# Sidebar contents
with st.sidebar:
    st.title("💬 Lead Generation")
    st.markdown(
        """
    ## About    
    💡 List of leads generated by Algorithm Dimension for Kara
    """
    )

user_input = st.text_input("Enter the url of the job postings page:")

if user_input:
    st.write(f"Searching for customers of {user_input}...")
    print("We are scrapping text data")
    html_raw_code = html_scrapping.extract_readable_text(user_input)
    print("Scrapping is done")
    print("GPT 3.5 is Working")
    df = llm_model.create_table_with_job(user_input, html_raw_code)
    df_lead = convert_to_lead_dataframe(df, TIME_WINDOW)
    df_lead.to_csv("output_example.csv")
    st.table(df_lead)